linters:
  enable:
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - goimports
  - gosimple
  - govet
  - ineffassign
  - megacheck
  - revive
  - rowserrcheck
  - staticcheck
  - typecheck
  - unconvert
  - unused
  disable:
  - errcheck

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gocognit

linters-settings:
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/loopholelabs/frpc-go
  govet:
    # enable or disable analyzers by name
    disable:
    - shadow
